
default: Makefile build build/pscript.a build/pscript.exe build/pscript_lexer.exe  run run_lexer   




SHELL:= /bin/sh
.SHELLFLAGS: -u -e  
#MAKEFLAGS:= s --warn-undefined-variables 
#MAKEFLAGS:= s 
.SUFFIXES: 
#.SILENT:
.NOTPARALLEL:
.EXPORT_ALL_VARIABLES:
.SECONDARY:
.PRECIOUS:
.ONESHELL:




clean:
	rm -Rf build 2>&1

clean-all: clean
	rm -Rf destroot run rundir run_lexer *~ .*~ src/*~ src/*.output COPYING_at_start_of_c_files    2>&1


Makefile: Makefile-gen.mkf
	@echo "--- \"Makefile-gen.mkf\" changed. Please type './configure' (or 'romake -f Makefile-gen.mkf') to update this Makefile ---"
	@false

build:
	mkdir -p build 2>&1 


install: destroot_do

destroot_do:
	rm -Rf destroot
	mkdir -p destroot
	mkdir -p destroot/bin
	mkdir -p destroot/lib
	mkdir -p destroot/src/src
	./run --copyright-cstr 2> destroot/src/src/pscript.h || true  
	cat src/pscript.h >> destroot/src/src/pscript.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_bytecode.h || true  
	cat src/pscript_bytecode.h >> destroot/src/src/pscript_bytecode.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_chunk.h || true  
	cat src/pscript_chunk.h >> destroot/src/src/pscript_chunk.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_code_parser.h || true  
	cat src/pscript_code_parser.h >> destroot/src/src/pscript_code_parser.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_const.h || true  
	cat src/pscript_const.h >> destroot/src/src/pscript_const.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_env.h || true  
	cat src/pscript_env.h >> destroot/src/src/pscript_env.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_exception.h || true  
	cat src/pscript_exception.h >> destroot/src/src/pscript_exception.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_ffiproc.h || true  
	cat src/pscript_ffiproc.h >> destroot/src/src/pscript_ffiproc.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_funproc.h || true  
	cat src/pscript_funproc.h >> destroot/src/src/pscript_funproc.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_global.h || true  
	cat src/pscript_global.h >> destroot/src/src/pscript_global.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_input.h || true  
	cat src/pscript_input.h >> destroot/src/src/pscript_input.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_inttype.h || true  
	cat src/pscript_inttype.h >> destroot/src/src/pscript_inttype.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_libproc.h || true  
	cat src/pscript_libproc.h >> destroot/src/src/pscript_libproc.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_mainproc.h || true  
	cat src/pscript_mainproc.h >> destroot/src/src/pscript_mainproc.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_mem.h || true  
	cat src/pscript_mem.h >> destroot/src/src/pscript_mem.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_menu.h || true  
	cat src/pscript_menu.h >> destroot/src/src/pscript_menu.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_parser.h || true  
	cat src/pscript_parser.h >> destroot/src/src/pscript_parser.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_stack.h || true  
	cat src/pscript_stack.h >> destroot/src/src/pscript_stack.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_string.h || true  
	cat src/pscript_string.h >> destroot/src/src/pscript_string.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_token.h || true  
	cat src/pscript_token.h >> destroot/src/src/pscript_token.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_token_automata.h || true  
	cat src/pscript_token_automata.h >> destroot/src/src/pscript_token_automata.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_token_parser.h || true  
	cat src/pscript_token_parser.h >> destroot/src/src/pscript_token_parser.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_token_type.h || true  
	cat src/pscript_token_type.h >> destroot/src/src/pscript_token_type.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_type.h || true  
	cat src/pscript_type.h >> destroot/src/src/pscript_type.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_value.h || true  
	cat src/pscript_value.h >> destroot/src/src/pscript_value.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_var.h || true  
	cat src/pscript_var.h >> destroot/src/src/pscript_var.h 
	./run --copyright-cstr 2> destroot/src/src/pscript_vm.h || true  
	cat src/pscript_vm.h >> destroot/src/src/pscript_vm.h 
	./run --copyright-cstr 2> destroot/src/src/main.c || true  
	cat src/main.c >> destroot/src/src/main.c 
	./run --copyright-cstr 2> destroot/src/src/main_lexer.c || true  
	cat src/main_lexer.c >> destroot/src/src/main_lexer.c 
	./run --copyright-cstr 2> destroot/src/src/pscript.c || true  
	cat src/pscript.c >> destroot/src/src/pscript.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_bytecode.c || true  
	cat src/pscript_bytecode.c >> destroot/src/src/pscript_bytecode.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_chunk.c || true  
	cat src/pscript_chunk.c >> destroot/src/src/pscript_chunk.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_code_parser.c || true  
	cat src/pscript_code_parser.c >> destroot/src/src/pscript_code_parser.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_const.c || true  
	cat src/pscript_const.c >> destroot/src/src/pscript_const.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_env.c || true  
	cat src/pscript_env.c >> destroot/src/src/pscript_env.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_exception.c || true  
	cat src/pscript_exception.c >> destroot/src/src/pscript_exception.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_ffiproc.c || true  
	cat src/pscript_ffiproc.c >> destroot/src/src/pscript_ffiproc.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_funproc.c || true  
	cat src/pscript_funproc.c >> destroot/src/src/pscript_funproc.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_input.c || true  
	cat src/pscript_input.c >> destroot/src/src/pscript_input.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_libproc.c || true  
	cat src/pscript_libproc.c >> destroot/src/src/pscript_libproc.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_mainproc.c || true  
	cat src/pscript_mainproc.c >> destroot/src/src/pscript_mainproc.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_mem.c || true  
	cat src/pscript_mem.c >> destroot/src/src/pscript_mem.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_menu.c || true  
	cat src/pscript_menu.c >> destroot/src/src/pscript_menu.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_parser.c || true  
	cat src/pscript_parser.c >> destroot/src/src/pscript_parser.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_stack.c || true  
	cat src/pscript_stack.c >> destroot/src/src/pscript_stack.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_string.c || true  
	cat src/pscript_string.c >> destroot/src/src/pscript_string.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_token.c || true  
	cat src/pscript_token.c >> destroot/src/src/pscript_token.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_token_automata.c || true  
	cat src/pscript_token_automata.c >> destroot/src/src/pscript_token_automata.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_token_parser.c || true  
	cat src/pscript_token_parser.c >> destroot/src/src/pscript_token_parser.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_token_type.c || true  
	cat src/pscript_token_type.c >> destroot/src/src/pscript_token_type.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_type.c || true  
	cat src/pscript_type.c >> destroot/src/src/pscript_type.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_value.c || true  
	cat src/pscript_value.c >> destroot/src/src/pscript_value.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_var.c || true  
	cat src/pscript_var.c >> destroot/src/src/pscript_var.c 
	./run --copyright-cstr 2> destroot/src/src/pscript_vm.c || true  
	cat src/pscript_vm.c >> destroot/src/src/pscript_vm.c 
	./run --copyright-cstr 2> destroot/src/src/lib__01__pre_header.ci || true  
	cat src/lib__01__pre_header.ci >> destroot/src/src/lib__01__pre_header.ci 
	./run --copyright-cstr 2> destroot/src/src/lib__02__header.ci || true  
	cat src/lib__02__header.ci >> destroot/src/src/lib__02__header.ci 
	./run --copyright-cstr 2> destroot/src/src/lib__03.ci || true  
	cat src/lib__03.ci >> destroot/src/src/lib__03.ci 
	./run --copyright-cstr 2> destroot/src/src/lib__04__string_stack.ci || true  
	cat src/lib__04__string_stack.ci >> destroot/src/src/lib__04__string_stack.ci 
	./run --copyright-cstr 2> destroot/src/src/lib__05__error_state.ci || true  
	cat src/lib__05__error_state.ci >> destroot/src/src/lib__05__error_state.ci 
	./run --copyright-cstr 2> destroot/src/src/lib__06__exception.ci || true  
	cat src/lib__06__exception.ci >> destroot/src/src/lib__06__exception.ci 
	./run --copyright-cstr 2> destroot/src/src/main_options.ci || true  
	cat src/main_options.ci >> destroot/src/src/main_options.ci 
	./run --copyright-cstr 2> destroot/src/src/pscript_funproc.ci || true  
	cat src/pscript_funproc.ci >> destroot/src/src/pscript_funproc.ci 
	./run --copyright-cstr 2> destroot/src/src/pscript_parser.ci || true  
	cat src/pscript_parser.ci >> destroot/src/src/pscript_parser.ci 
	./run --copyright-cstr 2> destroot/src/src/pvm_bytecode__type.ci || true  
	cat src/pvm_bytecode__type.ci >> destroot/src/src/pvm_bytecode__type.ci 
	mkdir -p destroot/include/pscript 
	ln destroot/src/src/pscript.h destroot/include/pscript/pscript.h 
	ln destroot/src/src/pscript_const.h destroot/include/pscript/pscript_const.h 
	ln destroot/src/src/pscript_env.h destroot/include/pscript/pscript_env.h 
	ln destroot/src/src/pscript_funproc.h destroot/include/pscript/pscript_funproc.h 
	ln destroot/src/src/pscript_ffiproc.h destroot/include/pscript/pscript_ffiproc.h 
	ln destroot/src/src/pscript_libproc.h destroot/include/pscript/pscript_libproc.h 
	ln destroot/src/src/pscript_bytecode.h destroot/include/pscript/pscript_bytecode.h 
	ln destroot/src/src/pscript_vm.h destroot/include/pscript/pscript_vm.h 
	ln destroot/src/src/pscript_value.h destroot/include/pscript/pscript_value.h 
	ln destroot/src/src/pscript_mainproc.h destroot/include/pscript/pscript_mainproc.h 
	ln destroot/src/src/pscript_mem.h destroot/include/pscript/pscript_mem.h 
	ln destroot/src/src/pscript_stack.h destroot/include/pscript/pscript_stack.h 
	ln destroot/src/src/pscript_string.h destroot/include/pscript/pscript_string.h 
	ln destroot/src/src/pscript_token.h destroot/include/pscript/pscript_token.h 
	ln destroot/src/src/pscript_token_type.h destroot/include/pscript/pscript_token_type.h 
	ln destroot/src/src/pscript_type.h destroot/include/pscript/pscript_type.h 
	ln destroot/src/src/pscript_token_parser.h destroot/include/pscript/pscript_token_parser.h 
	ln destroot/src/src/pscript_chunk.h destroot/include/pscript/pscript_chunk.h 
	ln destroot/src/src/pscript_parser.h destroot/include/pscript/pscript_parser.h 
	ln destroot/src/src/pscript_code_parser.h destroot/include/pscript/pscript_code_parser.h 
	ln destroot/src/src/pscript_var.h destroot/include/pscript/pscript_var.h 
	ln destroot/src/src/pscript_input.h destroot/include/pscript/pscript_input.h 
	ln destroot/src/src/pscript_menu.h destroot/include/pscript/pscript_menu.h 
	touch destroot/src/Makefile-gen.mkf 
	cat Makefile > destroot/src/Makefile 
	mkdir -p destroot/src/build
	cp -fp build/*.a destroot/src/build/
	ln -s ../src/build/pscript.a destroot/lib/libpscript.a 
	cp -fp build/*.exe destroot/src/build/
	ln -s ../src/build/pscript.exe destroot/bin/pscript 




alala:
	cp -fp src/pscript.h destroot/include/pscript/
	cp -fp src/pscript_const.h destroot/include/pscript/
	cp -fp src/pscript_env.h destroot/include/pscript/
	cp -fp src/pscript_funproc.h destroot/include/pscript/
	cp -fp src/pscript_mem.h destroot/include/pscript/
	cp -fp src/pscript_stack.h destroot/include/pscript/
	cp -fp src/pscript_string.h destroot/include/pscript/
	cp -fp src/pscript_token.h destroot/include/pscript/
	cp -fp src/pscript_type.h destroot/include/pscript/
	cp -fp src/pscript_var.h destroot/include/pscript/










run: build/pscript.exe
	rm -f run
	ln -s build/pscript.exe run

run_lexer: build/pscript_lexer.exe 
	rm -f run_lexer  2>&1
	ln -s build/pscript_lexer.exe run_lexer 








build/pscript.exe: build/main.o  build/pscript.a
	cc -o build/pscript.exe build/main.o build/pscript.a /home/romain/projects/libedit-20090923-3.0/destroot/lib/libedit.a  -ltermcap -lm   2>&1

build/pscript_lexer.exe: build/main_lexer.o build/pscript.a
	cc -o build/pscript_lexer.exe build/main_lexer.o build/pscript.a /home/romain/projects/libedit-20090923-3.0/destroot/lib/libedit.a  -ltermcap -lm   2>&1








build/pscript.a: build/pscript.o build/pscript_bytecode.o build/pscript_chunk.o build/pscript_code_parser.o build/pscript_const.o build/pscript_env.o build/pscript_exception.o build/pscript_ffiproc.o build/pscript_funproc.o build/pscript_input.o build/pscript_libproc.o build/pscript_mainproc.o build/pscript_mem.o build/pscript_menu.o build/pscript_parser.o build/pscript_stack.o build/pscript_string.o build/pscript_token.o build/pscript_token_automata.o build/pscript_token_parser.o build/pscript_token_type.o build/pscript_type.o build/pscript_value.o build/pscript_var.o build/pscript_vm.o
	ar -r -c build/pscript.a build/pscript.o build/pscript_bytecode.o build/pscript_chunk.o build/pscript_code_parser.o build/pscript_const.o build/pscript_env.o build/pscript_exception.o build/pscript_ffiproc.o build/pscript_funproc.o build/pscript_input.o build/pscript_libproc.o build/pscript_mainproc.o build/pscript_mem.o build/pscript_menu.o build/pscript_parser.o build/pscript_stack.o build/pscript_string.o build/pscript_token.o build/pscript_token_automata.o build/pscript_token_parser.o build/pscript_token_type.o build/pscript_type.o build/pscript_value.o build/pscript_var.o build/pscript_vm.o 2>&1
	ranlib build/pscript.a 2>&1



















build/main.o: src/main.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/main.c -o build/main.o  2>&1

build/main_lexer.o: src/main_lexer.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/main_lexer.c -o build/main_lexer.o  2>&1

build/pscript.o: src/pscript.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript.c -o build/pscript.o  2>&1

build/pscript_bytecode.o: src/pscript_bytecode.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_bytecode.c -o build/pscript_bytecode.o  2>&1

build/pscript_chunk.o: src/pscript_chunk.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_chunk.c -o build/pscript_chunk.o  2>&1

build/pscript_code_parser.o: src/pscript_code_parser.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_code_parser.c -o build/pscript_code_parser.o  2>&1

build/pscript_const.o: src/pscript_const.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_const.c -o build/pscript_const.o  2>&1

build/pscript_env.o: src/pscript_env.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_env.c -o build/pscript_env.o  2>&1

build/pscript_exception.o: src/pscript_exception.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_exception.c -o build/pscript_exception.o  2>&1

build/pscript_ffiproc.o: src/pscript_ffiproc.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_ffiproc.c -o build/pscript_ffiproc.o  2>&1

build/pscript_funproc.o: src/pscript_funproc.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_funproc.c -o build/pscript_funproc.o  2>&1

build/pscript_input.o: src/pscript_input.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_input.c -o build/pscript_input.o  2>&1

build/pscript_libproc.o: src/pscript_libproc.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_libproc.c -o build/pscript_libproc.o  2>&1

build/pscript_mainproc.o: src/pscript_mainproc.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_mainproc.c -o build/pscript_mainproc.o  2>&1

build/pscript_mem.o: src/pscript_mem.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_mem.c -o build/pscript_mem.o  2>&1

build/pscript_menu.o: src/pscript_menu.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_menu.c -o build/pscript_menu.o  2>&1

build/pscript_parser.o: src/pscript_parser.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_parser.c -o build/pscript_parser.o  2>&1

build/pscript_stack.o: src/pscript_stack.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_stack.c -o build/pscript_stack.o  2>&1

build/pscript_string.o: src/pscript_string.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_string.c -o build/pscript_string.o  2>&1

build/pscript_token.o: src/pscript_token.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_token.c -o build/pscript_token.o  2>&1

build/pscript_token_automata.o: src/pscript_token_automata.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_token_automata.c -o build/pscript_token_automata.o  2>&1

build/pscript_token_parser.o: src/pscript_token_parser.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_token_parser.c -o build/pscript_token_parser.o  2>&1

build/pscript_token_type.o: src/pscript_token_type.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_token_type.c -o build/pscript_token_type.o  2>&1

build/pscript_type.o: src/pscript_type.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_type.c -o build/pscript_type.o  2>&1

build/pscript_value.o: src/pscript_value.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_value.c -o build/pscript_value.o  2>&1

build/pscript_var.o: src/pscript_var.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_var.c -o build/pscript_var.o  2>&1

build/pscript_vm.o: src/pscript_vm.c src/pscript.h src/pscript_bytecode.h src/pscript_chunk.h src/pscript_code_parser.h src/pscript_const.h src/pscript_env.h src/pscript_exception.h src/pscript_ffiproc.h src/pscript_funproc.h src/pscript_global.h src/pscript_input.h src/pscript_inttype.h src/pscript_libproc.h src/pscript_mainproc.h src/pscript_mem.h src/pscript_menu.h src/pscript_parser.h src/pscript_stack.h src/pscript_string.h src/pscript_token.h src/pscript_token_automata.h src/pscript_token_parser.h src/pscript_token_type.h src/pscript_type.h src/pscript_value.h src/pscript_var.h src/pscript_vm.h src/lib__01__pre_header.ci src/lib__02__header.ci src/lib__03.ci src/lib__04__string_stack.ci src/lib__05__error_state.ci src/lib__06__exception.ci src/main_options.ci src/pscript_funproc.ci src/pscript_parser.ci src/pvm_bytecode__type.ci     
	cc -std=c99 -D_THREAD_SAFE -D_REENTRANT -D __DEBUG__ -D DEBUG  -O0 -Wall -fmessage-length=0 -fdiagnostics-show-location=once -fdiagnostics-show-option -Wnewline-eof -Wfatal-errors -Werror-implicit-function-declaration -fno-exceptions -fstack-check -Werror -W  -Wparentheses -fverbose-asm -fno-omit-frame-pointer -ffreestanding -fno-builtin -fno-builtin-printf -fno-builtin-abs -fno-builtin-strcpy -fno-builtin-strcat -fno-builtin-strlen -fno-builtin-bzero -fno-builtin-memset -fno-builtin-memcpy -fno-builtin-assert -fno-builtin-tolower -fno-builtin-toupper -fno-builtin-log -fno-builtin-alloca -fno-common -fno-exceptions -fno-non-call-exceptions -fno-asynchronous-unwind-tables -fno-inline -fno-inline-functions -fno-inline-functions  -gfull  -feliminate-unused-debug-types  -Wimplicit -Wreturn-type -Wcomment -Wpointer-arith -Wchar-subscripts -Wimplicit-int -Werror-implicit-function-declaration -Wmain -Wmissing-braces -Wmultichar -Wsequence-point -Wreturn-type  -Wstrict-prototypes -Wpacked -Wcast-qual -Wcast-align  -Wno-system-headers -Winline -Wformat-nonliteral -Wwrite-strings -Wmissing-field-initializers -Wsign-compare  -Wformat-zero-length -Wswitch -Wswitch-enum -Wswitch-default -Wnested-externs -Wunknown-pragmas -Wno-undef -Wno-redundant-decls -Wno-unused -Wno-unused-parameter -Wno-unused-function -Wno-switch-default -Wno-format-nonliteral -Wno-unsequenced -Wno-cast-align  -I /usr/X11R6/include  -I ./libs/SDL-1.2.15/destroot/include -I ./src/SDL_image -I ./src/SDL_mixer -I /home/romain/projects/libedit-20090923-3.0/destroot/include/     -c src/pscript_vm.c -o build/pscript_vm.o  2>&1















